[package]
name = "hanec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hane-kernel = { path="../hane-kernel" }
hane-syntax = { path="../hane-syntax" }

clap = { version = "4.1.1", features = ["derive"] }
